name: 'Set Calver'
description: 'Calculate CalVer version and set PACKAGE_VERSION environment variables.'
inputs:
  version_prefix:  # id of input
    default: ''
    required: false
    description: 'Version string prefix'
  default_branch:
    default: 'refs/heads/main'
    required: false
    description: 'Name of the default branch'
outputs:
  package_version: # id of output
    description: 'The version we determined'
runs:
  using: 'node16'
  main: 'src/index.js'
branding:
  icon: bookmark
  color: red